LANGUAGES = {
    "en": {
        "new_user_message": "🤚 <b>Welcome, wanderer!</b> \n\n🧌 You've entered the world of goblins. \nEarn gold, exchange it for tokens, invite friends, and build your goblin gang. \n\n👇 To start mining, subscribe to the channel @Angry_goblin.",
        "initiation_failed_message": "First, subscribe to the channel @Angry_goblin.",
        "welcome_message": "🤚 <b>Happy to see you in the goblin gang!</b> \n\nThe main rule in the world of goblins: the more members in your gang, the more you can earn. You'll receive 500 #Gold for every invited bandit. \nYour referral link is in the 👥 <b>Gang</b> section. \n\nTo earn gold, plunder the mine! Every 4 hours, go to the ☠️ <b>Plunder</b> section and click the Plunder button. \n\nSoon, there will be an 💪 Upgrades section, and you'll be able to plunder faster and take more loot at once. \n\n🗞 Stay updated in the channel.",
        "pillage_info_message": "☠️ Click Plunder to claim the gold for yourself. \n\n🕓 Plunder time: 4 hours. \n💰 Gold per plunder: 100 #Gold.",
        "pillage_success_message": "✅ Gold is yours! \n\nYou'll return home in 4 hours and can go plundering again.",
        "pillage_failure_message": "⏳ You head home with a heavy sack on your shoulders. \n\nNext plunder in: {reward_time}",
        "current_balance_message": "💰 You have {user_balance} #Gold. \n\nTo earn more, invite friends to the gang and plunder the mine! \n\n1 friend = 500 #Gold. \n1 plunder = 100 #Gold.",
        "twitter_link_message": "https://twitter.com/{TWITTER_USERNAME}/status/latest",
        "invalid_button_message": "No such button!",
        "language_choose_message": "Choose language:",
        "language_switched_message": "Language selected",
        "referrals_info_message": "👥 <b>You have {amount_of_referrals} goblins in your gang!</b> \n\n💰 Invite more friends and get more gold. \n\nYour referral link: \n\n<code>{base_url}{referral_code}</code>",
        "quests_list_message": "🧭 Complete quests to earn more gold!",
        "quests_list_empty_message": "No new quests yet",
        "daily_quest_message": "Repost our latest tweet and double all gold from plundering!",
        "start_another_bot_quest_message": "Open a partner bot",
        "subscribe_tg_channel_quest_message": "Subscribe to the partner channel",
        "daily_quest_completed_message": "Daily quest completed, reward received!",
        "daily_quest_failed_message": "Conditions not met, try again.",
        "pillage_button": "☠️ Plunder",
        "referrals_button": "👥 Gang",
        "balance_button": "💰 Balance",
        "quests_button": "🧭 Quests",
        "language_button": "🌐 Language",
        "claim_button": "Claim",
        "subscribe_tg_channel_button": "Subscribe to partner channel",
        "start_another_bot_button": "Enter partner bot",
        "daily_quest_button": "Daily Quest",
        "check_quest_button": "Check",
        "link_daily_quest_button": "Go to Twitter",
        "link_bot_quest_button": "Open bot",
        "link_subscribe_quest_button": "Subscribe",
        "initiation_button": "Begin journey",
        "invite_button": "Invite friends",
    },
    "ru": {
        "new_user_message": "🤚  <b>Привет, странник!</b> \n\n🧌 Ты попал в мир гоблинов. \nДобывай золото, меняй на токены, зови друзей и строй гоблинскую банду. \n\n👇 Чтобы начать добычу, подпишись на канал @Angry_goblin",
        "initiation_failed_message": "Сначала подпишись на канал @Angry_goblin.",
        "welcome_message": "🤚 <b>Рады видеть тебя в гоблинской банде!</b> \n\nГлавное правило в мире гоблинов: чем больше твоя банда, тем больше ты сможешь заработать. За каждого приглашенного бандита ты получишь 500 #Gold. \nТвоя реферальная ссылка в разделе 👥 <b>Банда.</b> \n\nЧтобы зарабатывать золотишко, грабь рудник! Каждые 4 часа заходи в раздел ☠️ <b>Грабеж</b> и жми на кнопку Ограбить.  \n\nСкоро появится раздел 💪 Улучшения и ты сможешь быстрее грабить и больше выносить за раз.  \n\n🗞 Следи за обновлениями в канале. ",
        "pillage_info_message": "☠️Нажми Ограбить, чтобы забрать золото себе. \n\n🕓 Время грабежа: 4 часа. \n💰 Золото за грабёж: 100 #Gold.",
        "pillage_success_message": "✅ Золото у тебя! \n\nЧерез 4 часа ты вернешься домой и сможешь снова отправиться на грабеж.",
        "pillage_failure_message": "⏳Ты идёшь домой с тяжелым мешком за плечами. \n\nСледующий грабеж через: {reward_time}",
        "current_balance_message": "💰 У тебя {user_balance} #Gold. \n\nЧтобы заработать больше, приглашай друзей в банду и грабь рудник! \n\n1 друг = 500 #Gold. \n1 грабеж 100 #Gold. ",
        "twitter_link_message": "https://twitter.com/{TWITTER_USERNAME}/status/latest",
        "invalid_button_message": "Нет такой кнопки!",
        "language_choose_message": "Выберите язык:",
        "language_switched_message": "Язык выбран",
        "referrals_info_message": "👥 <b>В твоей банде {amount_of_referrals} гоблинов!</b> \n\n💰 Зови больше друзей и получай больше золота. \n\nТвоя реферальная ссылка: \n\n<code>{base_url}{referral_code}</code>",
        "quests_list_message": "🧭 Выполняй квесты, чтобы получать больше золота!",
        "quests_list_empty_message": "Пока нет новых квестов",
        "daily_quest_message": "Сделай репост последнего нашего твита и удвой всё золото с грабежей!",
        "start_another_bot_quest_message": "Открой партнёрский бот",
        "subscribe_tg_channel_quest_message": "Подпишись на партнёрский канал",
        "daily_quest_completed_message": "Ежедневный квест выполнен, награда получена!",
        "daily_quest_failed_message": "Уcловия не выполнены, попробуй ещё раз.",
        "pillage_button": "☠️ Грабеж",
        "referrals_button": "👥 Банда",
        "balance_button": "💰 Баланс",
        "quests_button": "🧭 Квесты",
        "language_button": "🌐 Язык",
        "claim_button": "Забрать",
        "subscribe_tg_channel_button": "Подпишись на канал партнёра",
        "start_another_bot_button": "Зайди в партнёрский бот",
        "daily_quest_button": "Ежедневный квест",
        "check_quest_button": "Проверить",
        "link_daily_quest_button": "Перейти в твиттер",
        "link_bot_quest_button": "Открыть бот",
        "link_subscribe_quest_button": "Подписаться",
        "invite_button": "Пригласить друзей",
        "initiation_button": "Начать путешествие",
    }
}
